### ISSUE TITLE
Follow guidelines for use of Passbolt registered trademark

### ISSUE THREAD

**Issue by stripthis** [daniel-lynch/passbolt#3]
Hello,

Thank you for this project. As the founder of passbolt wanted to reach out to you with regards to trademark use. Please have a look at the guidelines: https://www.passbolt.com/credits/trademark-guidelines

Feel free to reach out to us if you have questions!

**Comment by daniel-lynch** [comment]
Hi @stripthis, thanks for creating passbolt! I believe https://github.com/daniel-lynch/py-passbolt/pull/6/files should fix this up? If not let me know. PR's are always appreciated ;) .

**Comment by stripthis** [comment]
Hello, 

The changes for the readme are good. 

However the name of the package is not, this can lead to confusion:
```
pip3 install passbolt
```

It is considered invalid under pip guidelines as well:
https://peps.python.org/pep-0541/

A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
(...)
- project violates copyright, trademarks, patents, or licenses;

**Comment by daniel-lynch** [comment]
@stripthis I've deleted the PyPI project. Do I have to change the internal package name as well? I plan on archiving the repo after this.

**Comment by stripthis** [comment]
Hello @daniel-lynch,

Thanks for this. The internal package or repo name is fine, as it's shown under your name.

I know it's not nice, but we have to enforce the trademark even to nice people, to protect it in the future from not-so-nice people. Thank you for your understanding.
